spring.application.name=mbcFinalProject1

spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.hikari.username=postgres
spring.datasource.hikari.password=1234

openapi.key=a913790eaa3034943cc340da8ef5b185195b7ea78dce8dc3183461115d62e68e
